"""
Stage 2: Downloader
===================
downloader.py

This script consumes the manifest generated by the Harvester and systematically 
downloads the native VTT/SRT subtitles from YouTube for each video. 
It uses 'cookies.txt' to authenticate and bypass anti-bot blocks.
"""
import os
import shutil
import yt_dlp

def download_subtitles_from_manifest(manifest_path="manifest_urls.txt"):
    output_dir = "Raw_Transcripts"

    # 1. The Auto-Wiper
    if os.path.exists(output_dir):
        print(f"🗑️ Wiping old {output_dir} folder...")
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)

    # Move playlist_name.txt into Raw_Transcripts if it exists so processor.py can find it
    if os.path.exists("playlist_name.txt"):
        shutil.copy("playlist_name.txt", os.path.join(output_dir, "playlist_name.txt"))

    if not os.path.exists(manifest_path):
        print(f"❌ Error: {manifest_path} not found. Please run harvester.py first.")
        return

    # Phase 2: Consume Manifest & Download Subtitles
    with open(manifest_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
        
    total_videos = len(lines)
    print(f"🚀 Found {total_videos} videos in manifest. Downloading subtitles one by one...")
    
    for index, line in enumerate(lines, start=1):
        line = line.strip()
        if not line:
            continue
            
        parts = line.split(',', 1)
        target_url = parts[0]
        video_title = parts[1] if len(parts) > 1 else f"Video_{index}"

        # Remove problematic characters from title
        safe_title = "".join([c for c in video_title if c.isalpha() or c.isdigit() or c==' ']).rstrip()

        phase2_opts = {
            'skip_download': True,
            'writesubtitles': True,
            'writeautomaticsub': True,
            'subtitleslangs': ['en', '.*-orig'],
            'outtmpl': f'{output_dir}/{index:03d}_{safe_title}.%(ext)s',
            'cookiefile': 'cookies.txt',
            'quiet': True,
            'no_warnings': True,
            'ignoreerrors': True, 
        }

        try:
            with yt_dlp.YoutubeDL(phase2_opts) as ydl:
                result = ydl.download([target_url])
                # yt-dlp returns 0 on success, 1 on failure
                if result != 0:
                    print(f"⚠️ FAILED: No subtitles exist on YouTube for [{video_title}] ({target_url})")
                else:
                    print(f"✅ Processed [{index}/{total_videos}]: {video_title}")
        except Exception as e:
            print(f"⚠️ FAILED: No subtitles exist on YouTube for [{video_title}] ({target_url}) - {str(e)}")

    print(f"\n🎉 Stage 1 Complete! Transcripts saved to {output_dir}")

if __name__ == "__main__":
    download_subtitles_from_manifest()
